services:
  web:
    container_name: codia_web
    build:
      context: ./src/web
      dockerfile: ../../docker/web/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api
    volumes:
      - ./src/web:/web
      - node_modules_web:/web/node_modules
    networks:
      - codia-network

  api:
    container_name: codia_api
    build:
      context: ./src/api
      dockerfile: ../../docker/api/Dockerfile
    environment:
      - PORT=3001
    ports:
      - 3001:3001
    depends_on:
      - db
    volumes:
      - ./src/api:/api
      - node_modules_api:/api/node_modules
    networks:
      - codia-network

  db:
    container_name: codia_db
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: codia
    volumes:
      - codia_db:/var/lib/mysql
    networks:
      - codia-network

volumes:
  codia_db:
  node_modules_web:
  node_modules_api:

networks:
  codia-network:
    driver: bridge
