services:
  web:
    container_name: codia_web
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - api
    volumes:
      - ./src/web:/web
    networks:
      - codia-network

  api:
    container_name: codia_api
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3001:3001
    depends_on:
      - db
    volumes:
      - ./src/api:/api
    networks:
      - codia-network

  db:
    container_name: codia_db
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: codia
    volumes:
      - codia_db:/var/lib/mysql
    networks:
      - codia-network

volumes:
  codia_db:

networks:
  codia-network:
    driver: bridge
